# Generated by Django 3.0.5 on 2020-05-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='image',
            field=models.ImageField(default='test.png', upload_to='static/img'),
            preserve_default=False,
        ),
    ]
