# Generated by Django 3.0.5 on 2020-05-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_auto_20200509_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='image',
            field=models.ImageField(upload_to='drinks/%y/%m/'),
        ),
    ]
