# Generated by Django 3.0.5 on 2020-05-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0004_auto_20200509_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='image',
            field=models.ImageField(upload_to='drinks/%Y/%m/%D'),
        ),
    ]
