# Generated by Django 3.0.5 on 2020-05-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0005_auto_20200509_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='image',
            field=models.ImageField(upload_to='drinks/%Y/%m'),
        ),
    ]
